name: amazing_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  camera: ^0.10.0+4
  image: ^3.2.2
  lottie: ^1.4.3
  google_sign_in: ^5.4.2
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  flutter_face_api: ^4.1.0
  onboarding: ^3.1.0
  shared_preferences: ^2.0.15
  # flutter_face_api_beta: ^0.0.71

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript.ttf
    - family: Montserrat
      fonts:
        - asset: fonts\Montserrat-Bold.ttf
          weight: 700
        - asset: fonts\Montserrat-Light.ttf
          weight: 100
        - asset: fonts\Montserrat-Medium.ttf
          weight: 500
        - asset: fonts\Montserrat-Regular.ttf

  uses-material-design: true